### PR TITLE
README Spelling fix

### PR DESCRIPTION
**Pull request by ghost**
As the title says

### CODE REVIEW

**Comment by MegaPika** [comment]
True for reviving but retalking is correct because we restart a conversation about so 🤷‍♂️.
Thanks ^^

**Comment by ghost** [comment]
Retalking is half correct. It doesn't sound terrible but it's informal and not in the Oxford Dictionary

**Comment by MegaPika** [comment]
who started a new conversation about reviving NintendoZone... is it correct ?

**Comment by ghost** [comment]
Its good!

**Pull request merged**
